eureka:
  instance:
    status-page-url: http://localhost:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 10001
spring:
  application:
    name: zipkin-service
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/zipkin?zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2b8&charset=utf8mb4&useSSL=false
    username: root
    password: wangyang
management:
  server:
    port: 11001
  metrics:
    web:
      server:
        auto-time-requests: false
zipkin:
  collector:
    rabbitmq:
      addresses: 192.168.30.199:5672
      password: admin
      username: admin
      queue: zipkin
  storage:
    type: mysql
