eureka:
  instance:
    status-page-url: http://localhost:${server.port}/swagger-ui.html
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 10001
spring:
  application:
    name: zipkin-service
management:
  server:
    port: 11001
  metrics:
    web:
      server:
        auto-time-requests: false


