eureka:
  instance:
    status-page-url: http://localhost:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 10001
spring:
  application:
    name: zipkin-service
  main:
    allow-bean-definition-overriding: true
management:
  server:
    port: 11001
  metrics:
    web:
      server:
        auto-time-requests: false
zipkin:
  collector:
    rabbitmq:
      addresses: 192.168.30.199:5672
      password: admin
      username: admin
      queue: zipkin
