server:
  port: 8081
spring:
  rabbitmq:
    host: 192.168.30.199
    port: 5672
    username: admin
    password: admin

  boot:
    admin:
      client:
        url: http://localhost:12001
        instance:
          service-base-url: http://localhost:8081
  zipkin:
    base-url: http://localhost:10001
    sleuth:
      sampler:
      percentage: 1.0
    sender:
      type: rabbit
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/java_box?&serverTimezone=GMT
    username: root
    password: wangyang
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 300
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis:
    type-aliases-package: com.wzy.pojo
    mapper-locations: classpath:mapper/*.xml
management:
  server:
    port: 15002
  endpoints:
      web:
        exposure:
          include: "*"
feign:
  hystrix:
    enabled: true



