eureka:
  instance:
    status-page-url: http://localhost:${server.port}/swagger-ui.html
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081
spring:
  application:
    name: user-service

  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/wx_shop
    username: root
    password: wangyang
    # druid 连接池
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 300
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

mybatis:
    type-aliases-package: com.wzy.pojo
    mapper-locations: classpath:mapper/*.xml

management:
  server:
    port: 9092



