server:
  port: 8009
management:
  server:
    port: 10007
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
feign:
  hystrix:
    enabled: true

ribbon:
  eager-load:
    enabled: true
    clients: SYSTEM-SERVICE,REDIS-SERVICE