client: lptnyy
secret: wangyang119
jwtSecret: wangyang119
server:
  port: 8006
management:
  endpoints:
    web:
      exposure:
        include: "*"

# 解决首次调用服务失败的问题
feign:
  hystrix:
    enabled: true
