server:
  port: 8010

management:
  server:
    port: 10009
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

feign:
  hystrix:
    enabled: true

