sharding.jdbc:
  data-sources:
    ds_master:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/pro_user?useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password: wangyang
    ds_slave_0:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/pro_user?useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password: wangyang
  master-slave-rule:
    name: ds_ms
    master-data-source-name: ds_master
    slave-data-source-names: ds_slave_0
    load-balance-algorithm-type: round_robin