security:
  oauth2:
    client:
      access-token-uri: http://localhost:8006/oauth/token
      user-authorization-uri: http://localhost:8006/oauth/authorize
      client-id: lptnyy
      authentication-scheme: header
      client-authentication-scheme: header
    resource:
      user-info-uri: http://localhost:8006/user
      prefer-token-info: false
      jwt:
        key-value: wangyang119
    not-intercept-url: /db/downloadZip,/ProUserRole/getList,/ProRoleMenu/getIdsList,/ProMenu/getIdsList,/file/download,/user/getUser,/instances,/actuator/**,/swagger-ui.html,/swagger**,/webjars/**,/springfox-swagger-ui/**,/swagger-resources/**,/v2/** #配置免oa验证的地址