server:
  port: 8007
management:
  server:
    port: 10010
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
feign:
  hystrix:
    enabled: true
oss:
  type: ali # file参数本地储存  ali参数阿里oss
  local-file-path: "system.dir"   # system.dir 项目运行的根目录  可以自定义路径 C： 或者 /root  等等 本地储存使用参数
  file-dns-url: https://wzyfiles.oss-cn-beijing.aliyuncs.com/  # 配置下载文件地址
  endpoint: oss-cn-beijing.aliyuncs.com  # 阿里配置参数
  access-key-id: LTAIuKbWST54Tbn6 # 阿里配置参数
  access-key-secret: JQNwCvfMwnBihg6aJhjRhs1AqUVimV # 阿里配置参数
  bucket-name: wzyfiles # 阿里使用参

spring:
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/pro_user?serverTimezone=Hongkong&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false  # serverTimezone=Hongkong 需要填上时区
          username: root
          password: wangyang
          driverClassName:  com.mysql.jdbc.Driver
        slave:
          url: jdbc:mysql://localhost:3306/pro_user?serverTimezone=Hongkong&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false  # serverTimezone=Hongkong 需要填上时区
          username: root
          password: wangyang
          driverClassName:  com.mysql.jdbc.Driver
      initial-size: 10 # 以下是连接池配置
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: druid
        login-password: 123456
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true

mybatis:
  type-aliases-package: com.wzy.oss.dto
  mapper-locations: classpath:mapper/*.xml

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl