webClient: lptnyy
webSecret: wangyang119
phoneClient: phoneClient
phoneSecret: wangyang119
redirectUris: 'http://www.baidu.com,http://localhost:7071/login,http://localhost:8085/update,http://localhost/login'

server:
  port: 8006
mybatis:
  type-aliases-package: com.wzy.pojo
  mapper-locations: classpath:mapper/*.xml
management:
  server:
    port: 10004
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  hystrix:
    enabled: true
