server:
  port: 8009
management:
  server:
    port: 10007
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  hystrix:
    enabled: true

ribbon:
  eager-load:
    enabled: true
    clients: USER-SERVICE,REDIS-SERVICE