server:
  port: 8008
mybatis:
  type-aliases-package: com.wzy.pojo
  mapper-locations: classpath:mapper/*.xml
management:
  server:
    port: 10006
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  hystrix:
    enabled: true

ribbon:
  eager-load:
    enabled: true
    clients: REDIS-SERVICE