server:
  port: 8004
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/zipkin?zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2b8&charset=utf8mb4&useSSL=false
    username: root
    password: wangyang
  main:
    allow-bean-definition-overriding: true
zipkin:
  collector:
    rabbitmq:
      addresses: 106.54.138.78:5672
      password: wangyang119
      username: lptnyy
      queue: zipkin
  storage:
    type: mysql
management:
  server:
    port: 10002
  metrics:
    web:
      server:
        auto-time-requests: false
