server:
  port: 8004
spring:
  main:
    allow-bean-definition-overriding: true
zipkin:
  collector:
    rabbitmq:
      addresses: 106.54.138.78:5672
      password: wangyang119
      username: lptnyy
      queue: zipkin
  storage:
    type: mysql
management:
  server:
    port: 10002
  metrics:
    web:
      server:
        auto-time-requests: false
