server:
  port: 8101
  servlet:
    session:
      cookie:
        name: zuul_cookie

management:
  server:
    port: 10008
  endpoints:
    web:
      exposure:
        include: "*"

zuul:
  routes:
    user:
      path: /user/**
      serviceId: USER-SERVICE-RESTFULL
    auth:
      path: /auth/**
      serviceId: SSO-SERVICE
    config:
      path: /config/**
      serviceId: CONFIG-SERVICE
  sensitive-headers:
  - Cookie,Set-Cookie,Authorization
