spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/${config} # 搜索src/main/resource 下的properties文件夹下的文件

  bus:
    trace:
      enabled: true # 启用日志跟踪
  boot:
    admin:
      client:
        url: http://${config-service}:12001
        instance:
          service-base-url: http://${admin-service}:8081

  profiles:
    active: native  # 配置使用本地储存
  rabbitmq:
    host: 192.168.30.199
    port: 5672
    username: admin
    password: admin
server:
  port: 13001
  tomcat:
    max-http-post-size: 0
eureka:
  client:
    service-url:
      default-zone: http://${eureka-service}:8761/eureka

management:
  server:
    port: 9096
  endpoints:
    web:
      exposure:
        include: "*" # 暴露端点


