spring:
  application:
    name: eureka-service
server:
  port: 8761
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    fetch-registry: false
    register-with-eureka: false