eureka:
  instance:
    status-page-url: http://localhost:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 12001
spring:
  application:
    name: admin-service-ui




