server:
  port: 8765

eureka:
  instance:
    status-page-url: http://localhost:${server.port}/swagger-ui.html
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  boot:
    admin:
      client:
        url: http://localhost:12001
  application:
    name: user-service-web
  zipkin:
    base-url: http://localhost:10001
    sleuth:
      sampler:
      percentage: 1.0
feign:
  hystrix:
    enabled: true

management:
  server:
    port: 9093
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always