server:
  port: 8004
spring:
  main:
    allow-bean-definition-overriding: true
zipkin:
  collector:
    rabbitmq:
      addresses: 192.168.0.106:30001
      password: admin
      username: admin
      queue: zipkin
  storage:
    type: mysql
management:
  server:
    port: 10002
  metrics:
    web:
      server:
        auto-time-requests: false
