client_id: lptnyy
secret: wangyang119
server:
  port: 8083
mybatis:
  type-aliases-package: com.wzy.pojo
  mapper-locations: classpath:mapper/*.xml
management:
  server:
    port: 15005
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  hystrix:
    enabled: true
