server:
  port: 8081
mybatis:
  type-aliases-package: com.wzy.pojo
  mapper-locations: classpath:mapper/*.xml
management:
  server:
    port: 15002
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  hystrix:
    enabled: true
