server:
  port: 8091
spring:
  rabbitmq:
    host: 192.168.30.199
    port: 5672
    username: admin
    password: admin

  zipkin:
    base-url: http://localhost:10001
    sleuth:
      sampler:
      percentage: 1.0
  boot:
    admin:
      client:
        url: http://localhost:12001

management:
  server:
    port: 9001
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
      health:
        show-details: always




