spring:
  application:
    name: eureka-service
  boot:
    admin:
      client:
        url: http://${ADMIN-SERVICE}:8003
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA-SERVICE}:8001/eureka
    fetch-registry: false
    register-with-eureka: false

management:
  server:
    port: 10000
  endpoints:
    web:
      exposure:
        include: "*" # 暴露端点