server:
  port: 7071

eureka:
  instance:
    status-page-url: http://localhost:${server.port}/swagger-ui.html
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: zuul-service
  boot:
    admin:
      client:
        url: http://localhost:12001
  zipkin:
    base-url: http://localhost:10001
    sleuth:
      sampler:
      percentage: 1.0
    sender:
      type: web  # 引入mq 不这么设置会冲突

management:
  server:
    port: 9094
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

security:
  oauth2:
    client:
      access-token-uri: http://localhost:8083/oauth/token
      user-authorization-uri: http://localhost:8083/oauth/authorize
      client-id: webapp
    resource:
      user-info-uri: http://localhost:8083/user
      prefer-token-info: false
      jwt:
        key-value: secret

zuul:
  routes:
    user:
      path: /user/**
      serviceId: user-service-web


