server:
  port: 7071

eureka:
  instance:
    status-page-url: http://localhost:${server.port}/swagger-ui.html
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: zuul-service
  boot:
    admin:
      client:
        url: http://localhost:12001
  zipkin:
    base-url: http://localhost:10001
    sleuth:
      sampler:
      percentage: 1.0
    sender:
      type: web  # 引入mq 不这么设置会冲突

management:
  server:
    port: 9094
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
zuul:
  routes:
    user:
      path: /user/**
      serviceId: user-service-web



