spring:
  redis:
    database: 0
    host: 192.168.0.107
    port: 30000
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    timeout: 10000