server:
  port: 7071
  servlet:
    session:
      cookie:
        name: zuulcookie
eureka:
  instance:
    status-page-url: http://localhost:${server.port}/swagger-ui.html
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  redis:
    database: 0
    host: 192.168.30.199
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    timeout: 10000

  application:
    name: zuul-service
  boot:
    admin:
      client:
        url: http://localhost:12001
  zipkin:
    base-url: http://localhost:10001
    sleuth:
      sampler:
      percentage: 1.0
    sender:
      type: web  # 引入mq 不这么设置会冲突
  jta:
    atomikos:
      connectionfactory:
        ignore-session-transacted-flag:
  session:
    store-type: redis

management:
  server:
    port: 9094
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

security:
  oauth2:
    client:
      access-token-uri: http://localhost:8083/oauth/token
      user-authorization-uri: http://localhost:8083/oauth/authorize
      client-id: lptnyy
      authentication-scheme: header
      client-authentication-scheme: header
    resource:
      user-info-uri: http://localhost:8083/user
      prefer-token-info: false
      jwt:
        key-value: secret
zuul:
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000
  routes:
    web:
      path: /static/**
      url: http://localhost:81
    role:
      path: /**
      serviceId: role-service-web
    user:
      path: /web/user/**
      serviceId: user-service-web
  sensitive-headers:
  - Cookie,Set-Cookie,Authorization
feign:
  httpclient:
    enabled: true

logging:
  level:
    root: debug